### ISSUE TITLE
Need RegOpenKeyEx()

### ISSUE THREAD

**Issue by rodrigc** [opalmer/pywincffi#128]
In Twisted, I tried to replace pywin32 with pywincffi: https://github.com/twisted/twisted/pull/920

I found that the following are not in pywincffi:

win32api.RegOpenKeyEx()
win32api.RegQueryValueEx()
win32api.RegQueryValueEx()

@opalmer can you add them?

**Comment by opalmer** [comment]
@rodrigc could you use the winreg module instead?

https://docs.python.org/3/library/winreg.html#module-winreg
https://docs.python.org/2/library/_winreg.html#module-_winreg

I didn't include these functions in #69 originally because the code calling those functions had been deprecated and the standard library appeared to have the necessary support already. It also avoids a few layers of abstraction by not calling into pywincffi for these particular functions.

**Comment by rodrigc** [comment]
OK, please review this: https://github.com/twisted/twisted/pull/921

**Comment by opalmer** [comment]
Thanks, reviewed. I'm going to go head and close this.
